export const State=[
    {id:'1',name:'Andaman and nicobar islands'},
    {id:'2',name:'Andhra Pradesh'},
    {id:'3',name:'Arunachal Pradesh'},
    {id:'4',name:'Assam'},
    {id:'5',name:'Bihar'},
    {id:'6',name:'Chandigarh'},
    {id:'7',name:'Chhattisgarh'},
    {id:'8',name:'Delhi'},
    {id:'9',name:'Goa'},
    {id:'10',name:'Gujarat'},
    {id:'11',name:'Haryana'},
    {id:'12',name:'Himachal Pradesh'},
    {id:'13',name:'Jammu and Kashmir'},
    {id:'14',name:'Jharkhand'},
    {id:'15',name:'Karnataka'},
    {id:'16',name:'Kerala'},
    {id:'17',name:'Ladakh'},
    {id:'18',name:'Lakshadweep'},
    {id:'19',name:'Madhya Pradesh'},
    {id:'20',name:'Maharashtra'},
    {id:'21',name:'Manipur'},
    {id:'22',name:'Meghalaya'},
    {id:'23',name:'Mizoram'},
    {id:'24',name:'Na'},
    {id:'25',name:'Nagaland'},
    {id:'26',name:'Orisha'},
    {id:'27',name:'Pan India'},
    {id:'28',name:'Puducherry'},
    {id:'29',name:'Punjab'},
    {id:'30',name:'Rajasthan'},
    {id:'30',name:'sikkim'},
    {id:'32',name:'Tamil Nadu'},
    {id:'33',name:'Telangana'},
    {id:'34',name:'Dadar and Nagar haveli and daman and diu'},
    {id:'35',name:'Tripura'},
    {id:'36',name:'Uttar Pradesh'},
    {id:'37',name:'Uttarakhand'},
    {id:'38',name:'West Bengal'}

]
export const City=[
    {id:'1',stateId:'1',name:'Nicobars'},
    {id:'2',stateId:'1',name:'North and middle andaman'},
    {id:'3',stateId:'1',name:'South andaman'},
    {id:'4',stateId:'2',name:'Ananatpur'},
    {id:'5',stateId:'2',name:'Chittoor'},
    {id:'6',stateId:'2',name:'East Godavari'},
    {id:'7',stateId:'2',name:'Guntur'},
    {id:'8',stateId:'2',name:'Krishna'},
    {id:'9',stateId:'2',name:'Kurnool'},
    {id:'10',stateId:'2',name:'Prakasam'},
    {id:'11',stateId:'2',name:'SPSR Nellore'},
    {id:'12',stateId:'2',name:'Srikakulam'},
    {id:'13',stateId:'2',name:'Visakhapatnam'},
    {id:'14',stateId:'2',name:'Vizianagaram'},
    {id:'15',stateId:'2',name:'West Godavari'},
    {id:'16',stateId:'2',name:'Y.S.R'},
    {id:'17',stateId:'3',name:'Anjan'},
    {id:'18',stateId:'3',name:'Changlang'},
    {id:'19',stateId:'3',name:'Dibang Valley'},
    {id:'20',stateId:'3',name:'East Kameng'},
    {id:'21',stateId:'3',name:'East Siang'},
    {id:'22',stateId:'3',name:'Kamle'},
    {id:'23',stateId:'3',name:'Kra Daadi'},
    {id:'24',stateId:'3',name:'Kurung Kumey'},
    {id:'25',stateId:'3',name:'Leparada'},
    {id:'26',stateId:'3',name:'Lohit'},
    {id:'27',stateId:'3',name:'Longding'},
    {id:'28',stateId:'3',name:'Lower Dibang Valley'},
    {id:'29',stateId:'3',name:'Lower Siang'},
    {id:'30',stateId:'3',name:'Lower Subansiri'},
    {id:'31',stateId:'3',name:'Namsai'},
    {id:'32',stateId:'3',name:'Pakke Kessang'},
    {id:'33',stateId:'3',name:'Papum Pare'},
    {id:'34',stateId:'3',name:'Shi Yomi'},
    {id:'35',stateId:'3',name:'Siang'},
    {id:'36',stateId:'3',name:'Tawang'},
    {id:'37',stateId:'3',name:'Tirap'},
    {id:'38',stateId:'3',name:'Upper Siang'},
    {id:'40',stateId:'3',name:'Upper Subansiri'},
    {id:'41',stateId:'3',name:'West Kameng'},
    {id:'42',stateId:'3',name:'West Siang'},
    {id:'43',stateId:'4',name:'Baksa'},
    {id:'44',stateId:'4',name:'Barpeta'},
    {id:'45',stateId:'4',name:'Biswanath'},
    {id:'46',stateId:'4',name:'Bongaigaon'},
    {id:'47',stateId:'4',name:'Cachar'},
    {id:'48',stateId:'4',name:'Charaidio'},
    {id:'49',stateId:'4',name:'Chirang'},
    {id:'50',stateId:'4',name:'Darrang'},
    {id:'51',stateId:'4',name:'Dhemaji'},
    {id:'52',stateId:'4',name:'Dhubri'},
    {id:'53',stateId:'4',name:'Dibrugarh'},
    {id:'54',stateId:'4',name:'Dima Hasao'},
    {id:'55',stateId:'4',name:'Goalpara'},
    {id:'56',stateId:'4',name:'Golaghat'},
    {id:'57',stateId:'4',name:'Hailakandi'},
    {id:'58',stateId:'4',name:'Hojai'},
    {id:'59',stateId:'4',name:'Jorhat'},
    {id:'60',stateId:'4',name:'Kamrup'},
    {id:'61',stateId:'4',name:'Kamrup Metro'},
    {id:'62',stateId:'4',name:'Kabri Anglong'},
    {id:'63',stateId:'4',name:'Karimganj'},
    {id:'64',stateId:'4',name:'Kokrajhar'},
    {id:'65',stateId:'4',name:'Lakhimpur'},
    {id:'66',stateId:'4',name:'Majuli'},
    {id:'67',stateId:'4',name:'Marigaon'},
    {id:'68',stateId:'4',name:'Nagaon'},
    {id:'69',stateId:'4',name:'Nalbari'},
    {id:'70',stateId:'4',name:'Sivasagar'},
    {id:'71',stateId:'4',name:'Sonitpur'},
    {id:'72',stateId:'4',name:'South Salmara Mancachar'},
    {id:'73',stateId:'4',name:'Tinsukia'},
    {id:'74',stateId:'4',name:'Udalguri'},
    {id:'75',stateId:'4',name:'West Karbi Anglong'},
    {id:'76',stateId:'5',name:'Araria'},
    {id:'77',stateId:'5',name:'Arwal'},
    {id:'78',stateId:'5',name:'Aurangabad'},
    {id:'79',stateId:'5',name:'Banka'},
    {id:'80',stateId:'5',name:'Begusarai'},
    {id:'81',stateId:'5',name:'Bhagalpur'},
    {id:'82',stateId:'5',name:'Bhojpur'},
    {id:'83',stateId:'5',name:'Buxar'},
    {id:'84',stateId:'5',name:'Darbhanga'},
    {id:'85',stateId:'5',name:'Gaya'},
    {id:'86',stateId:'5',name:'Gopalganj'},
    {id:'87',stateId:'5',name:'Jamui'},
    {id:'88',stateId:'5',name:'Jehanabad'},
    {id:'89',stateId:'5',name:'Kaimur(Bhabua)'},
    {id:'90',stateId:'5',name:'Kathpur'},
    {id:'91',stateId:'5',name:'Khagaria'},
    {id:'92',stateId:'5',name:'Kishanganj'},
    {id:'93',stateId:'5',name:'Lakhisarai'},
    {id:'94',stateId:'5',name:'Madhepura'},
    {id:'95',stateId:'5',name:'Madhubani'},
    {id:'96',stateId:'5',name:'Munger'},
    {id:'97',stateId:'5',name:'Muzaffarpur'},
    {id:'98',stateId:'5',name:'Nalanda'},
    {id:'99',stateId:'5',name:'Nawada'},
    {id:'100',stateId:'5',name:'Pashchim Champaran'},
    {id:'101',stateId:'5',name:'Patna'},
    {id:'102',stateId:'5',name:'Purbi Champaran'},
    {id:'103',stateId:'5',name:'Purnia'},
    {id:'104',stateId:'5',name:'Rohtas'},
    {id:'105',stateId:'5',name:'Saharsa'},
    {id:'106',stateId:'5',name:'Samastipur'},
    {id:'107',stateId:'5',name:'Saran'},
    {id:'108',stateId:'5',name:'Sheikpura'},
    {id:'109',stateId:'5',name:'Sheohar'},
    {id:'110',stateId:'5',name:'Sitamarhi'},
    {id:'111',stateId:'5',name:'Siwan'},
    {id:'112',stateId:'5',name:'Supaul'},
    {id:'113',stateId:'5',name:'Vaishali'},
    {id:'114',stateId:'6',name:'Chandigarh'},
    {id:'115',stateId:'7',name:'Balod'},
    {id:'116',stateId:'7',name:'Baloda Bazar'},
    {id:'117',stateId:'7',name:'Balrampur'},
    {id:'118',stateId:'7',name:'Bastar'},
    {id:'119',stateId:'7',name:'Bemetara'},
    {id:'120',stateId:'7',name:'Bijapur'},
    {id:'121',stateId:'7',name:'Bilaspur'},
    {id:'122',stateId:'7',name:'Dantewada'},
    {id:'123',stateId:'7',name:'Dhamtari'},
    {id:'124',stateId:'7',name:'Durg'},
    {id:'125',stateId:'7',name:'Gariyaband'},
    {id:'126',stateId:'7',name:'Gaurella Pendra Marwahi'},
    {id:'127',stateId:'7',name:'Janjgir-Champa'},
    {id:'128',stateId:'7',name:'Jashpur'},
    {id:'129',stateId:'7',name:'Kabirdham'},
    {id:'130',stateId:'7',name:'Kanker'},
    {id:'131',stateId:'7',name:'Kondagaon'},
    {id:'132',stateId:'7',name:'Korba'},
    {id:'133',stateId:'7',name:'Koriya'},
    {id:'134',stateId:'7',name:'Mahasamund'},
    {id:'135',stateId:'7',name:'Mungeli'},
    {id:'136',stateId:'7',name:'Narayanpur'},
    {id:'137',stateId:'7',name:'Raigarh'},
    {id:'138',stateId:'7',name:'Raipur'},
    {id:'139',stateId:'7',name:'Rajnandgaon'},
    {id:'140',stateId:'7',name:'Sukma'},
    {id:'141',stateId:'7',name:'Surajpur'},
    {id:'142',stateId:'7',name:'Surguja'},
    {id:'143',stateId:'8',name:'Central'},
    {id:'145',stateId:'8',name:'East'},
    {id:'146',stateId:'8',name:'New Delhi'},
    {id:'147',stateId:'8',name:'North'},
    {id:'148',stateId:'8',name:'North East'},
    {id:'149',stateId:'8',name:'North West'},
    {id:'150',stateId:'8',name:'Shahdara'},
    {id:'151',stateId:'8',name:'South'},
    {id:'152',stateId:'8',name:'South East'},
    {id:'153',stateId:'8',name:'South West'},
    {id:'154',stateId:'8',name:'West'},
    {id:'155',stateId:'9',name:'North Goa'},
    {id:'156',stateId:'9',name:'South Goa'},
    {id:'157',stateId:'10',name:'Ahmedabad'},
    {id:'1510',stateId:'10',name:'Amreli'},
    {id:'159',stateId:'10',name:'Anand'},
    {id:'160',stateId:'10',name:'Arvalli'},
    {id:'161',stateId:'10',name:'Banas Kantha'},
    {id:'162',stateId:'10',name:'Bharuch'},
    {id:'163',stateId:'10',name:'Bhavnagar'},
    {id:'164',stateId:'10',name:'Botad'},
    {id:'165',stateId:'10',name:'Chhotaudepur'},
    {id:'166',stateId:'10',name:'Dang'},
    {id:'167',stateId:'10',name:'Devbhumi Dwarka'},
    {id:'1610',stateId:'10',name:'Dohad'},
    {id:'169',stateId:'10',name:'Gandhi Nagar'},
    {id:'170',stateId:'10',name:'Gir Somnath'},
    {id:'171',stateId:'10',name:'Jam Nagar'},
    {id:'172',stateId:'10',name:'Junagadh'},
    {id:'173',stateId:'10',name:'Kachchh'},
    {id:'174',stateId:'10',name:'Kheda'},
    {id:'175',stateId:'10',name:'Mahesana'},
    {id:'176',stateId:'10',name:'Mahisagar'},
    {id:'177',stateId:'10',name:'Morbi'},
    {id:'178',stateId:'10',name:'Narmada'},
    {id:'179',stateId:'10',name:'Navsari'},
    {id:'180',stateId:'10',name:'Panch Mahals'},
    {id:'181',stateId:'10',name:'Patan'},
    {id:'182',stateId:'10',name:'Porbandar'},
    {id:'183',stateId:'10',name:'Rajkot'},
    {id:'184',stateId:'10',name:'Sabar Kantha'},
    {id:'185',stateId:'10',name:'Surat'},
    {id:'186',stateId:'10',name:'SurendraNagar'},
    {id:'187',stateId:'10',name:'Tapi'},
    {id:'188',stateId:'10',name:'Vadodara'},
    {id:'189',stateId:'10',name:'Valsad'},
    {id:'190',stateId:'11',name:'Ambala'},
    {id:'191',stateId:'11',name:'Bhiwani'},
    {id:'192',stateId:'11',name:'Charki Dadri'},
    {id:'193',stateId:'11',name:'Faridabad'},
    {id:'194',stateId:'11',name:'Fatehabad'},
    {id:'195',stateId:'11',name:'Gurugram'},
    {id:'196',stateId:'11',name:'Hisar'},
    {id:'197',stateId:'11',name:'Jhajjar'},
    {id:'198',stateId:'11',name:'Jind'},
    {id:'199',stateId:'11',name:'Kaithal'},
    {id:'200',stateId:'11',name:'Karnal'},
    {id:'201',stateId:'11',name:'Kurukshetra'},
    {id:'202',stateId:'11',name:'Mahendragarh'},
    {id:'203',stateId:'11',name:'Nuh'},
    {id:'204',stateId:'11',name:'Palwal'},
    {id:'205',stateId:'11',name:'Panchkula'},
    {id:'206',stateId:'11',name:'Panipat'},
    {id:'207',stateId:'11',name:'Rewari'},
    {id:'208',stateId:'11',name:'Rohtak'},
    {id:'209',stateId:'11',name:'Sisra'},
    {id:'210',stateId:'11',name:'Sonipat'},
    {id:'211',stateId:'11',name:'Yamunanagar'},
    {id:'212',stateId:'12',name:'Bilaspur'},
    {id:'213',stateId:'12',name:'Chamba'},
    {id:'214',stateId:'12',name:'Hamirpur'},
    {id:'215',stateId:'12',name:'Kangra'},
    {id:'216',stateId:'12',name:'Kinnaur'},
    {id:'217',stateId:'12',name:'Kullu'},
    {id:'218',stateId:'12',name:'Lahul and Spiti'},
    {id:'219',stateId:'12',name:'Mandi'},
    {id:'220',stateId:'12',name:'Shimla'},
    {id:'221',stateId:'12',name:'Sirmaur'},
    {id:'222',stateId:'12',name:'Solan'},
    {id:'223',stateId:'12',name:'Una'},
    {id:'224',stateId:'13',name:'Anantnag'},
    {id:'225',stateId:'13',name:'Bandipora'},
    {id:'226',stateId:'13',name:'Baramulla'},
    {id:'227',stateId:'13',name:'Budgam'},
    {id:'228',stateId:'13',name:'Doda'},
    {id:'229',stateId:'13',name:'Ganderbal'},
    {id:'230',stateId:'13',name:'Jammu'},
    {id:'231',stateId:'13',name:'Kathua'},
    {id:'232',stateId:'13',name:'Kishtwar'},
    {id:'233',stateId:'13',name:'Kulgam'},
    {id:'234',stateId:'13',name:'Kupwara'},
    {id:'235',stateId:'13',name:'Poonch'},
    {id:'236',stateId:'13',name:'Pulwama'},
    {id:'237',stateId:'13',name:'Rajouri'},
    {id:'238',stateId:'13',name:'Ramban'},
    {id:'239',stateId:'13',name:'Reasi'},
    {id:'240',stateId:'13',name:'Samba'},
    {id:'241',stateId:'13',name:'Shopian'},
    {id:'242',stateId:'13',name:'Srinagar'},
    {id:'243',stateId:'13',name:'Udhampur'},
    {id:'244',stateId:'14',name:'Bokaro'},
    {id:'245',stateId:'14',name:'Chatra'},
    {id:'246',stateId:'14',name:'Deoghar'},
    {id:'247',stateId:'14',name:'Dhanbad'},
    {id:'248',stateId:'14',name:'Dhumka'},
    {id:'249',stateId:'14',name:'East Singhbum'},
    {id:'250',stateId:'14',name:'Gharwa'},
    {id:'251',stateId:'14',name:'Giridih'},
    {id:'252',stateId:'14',name:'Godda'},
    {id:'253',stateId:'14',name:'Gumla'},
    {id:'254',stateId:'14',name:'Hazaribagh'},
    {id:'255',stateId:'14',name:'Jamtara'},
    {id:'256',stateId:'14',name:'Khunti'},
    {id:'257',stateId:'14',name:'Koderma'},
    {id:'258',stateId:'14',name:'Latehar'},
    {id:'259',stateId:'14',name:'Lohardaga'},
    {id:'260',stateId:'14',name:'Pakur'},
    {id:'261',stateId:'14',name:'Paluma'},
    {id:'262',stateId:'14',name:'Ramgarh'},
    {id:'263',stateId:'14',name:'Ranchi'},
    {id:'264',stateId:'14',name:'Sahebganj'},
    {id:'265',stateId:'14',name:'Saraikela Kharsawan'},
    {id:'266',stateId:'14',name:'Simdega'},
    {id:'267',stateId:'14',name:'West Singhbhum'},
    {id:'268',stateId:'15',name:'Bagalkote'},
    {id:'269',stateId:'15',name:'Ballari'},
    {id:'270',stateId:'15',name:'Belagavi'},
    {id:'271',stateId:'15',name:'Bengaluru Urban'},
    {id:'272',stateId:'15',name:'Bengaluru Rural'},
    {id:'273',stateId:'15',name:'Bidar'},
    {id:'274',stateId:'15',name:'Chamarajanagara'},
    {id:'275',stateId:'15',name:'Chikkaballapura'},
    {id:'276',stateId:'15',name:'Chikkamagaluru'},
    {id:'277',stateId:'15',name:'Chitradurga'},
    {id:'278',stateId:'15',name:'Dikshina Kannada'},
    {id:'279',stateId:'15',name:'Davangere'},
    {id:'280',stateId:'15',name:'Dharwad'},
    {id:'281',stateId:'15',name:'Gadag'},
    {id:'282',stateId:'15',name:'Hassan'},
    {id:'283',stateId:'15',name:'Haveri'},
    {id:'284',stateId:'15',name:'Kalaburagi'},
    {id:'285',stateId:'15',name:'Kodagu'},
    {id:'286',stateId:'15',name:'Kolar'},
    {id:'287',stateId:'15',name:'Koppal'},
    {id:'288',stateId:'15',name:'Madhya'},
    {id:'289',stateId:'15',name:'Mysuru'},
    {id:'290',stateId:'15',name:'Raichur'},
    {id:'291',stateId:'15',name:'Ramanagara'},
    {id:'292',stateId:'15',name:'Shivamogga'},
    {id:'293',stateId:'15',name:'Tumakuru'},
    {id:'294',stateId:'15',name:'Udupi'},
    {id:'295',stateId:'15',name:'Uttara Kannada'},
    {id:'296',stateId:'15',name:'Vijayapura'},
    {id:'297',stateId:'15',name:'Yadgir'},
    {id:'298',stateId:'16',name:'Alappuzha'},
    {id:'299',stateId:'16',name:'Ernakulam'},
    {id:'300',stateId:'16',name:'Idukki'},
    {id:'301',stateId:'16',name:'Kannur'},
    {id:'302',stateId:'16',name:'Kasaragod'},
    {id:'303',stateId:'16',name:'Kollam'},
    {id:'304',stateId:'16',name:'Kottayam'},
    {id:'305',stateId:'16',name:'Kozhikode'},
    {id:'306',stateId:'16',name:'Malappuram'},
    {id:'307',stateId:'16',name:'Palakkad'},
    {id:'308',stateId:'16',name:'Pathanamthitta'},
    {id:'309',stateId:'16',name:'Thiruvananthapuram'},
    {id:'310',stateId:'16',name:'Thrissur'},
    {id:'311',stateId:'16',name:'Wayanad'},
    {id:'312',stateId:'17',name:'Kargil'},
    {id:'313',stateId:'17',name:'Leh Ladakh'},
    {id:'314',stateId:'18',name:'Lakshadweep District'},
    {id:'315',stateId:'19',name:'Agar Malwa'},
    {id:'316',stateId:'19',name:'Alirajpur'},
    {id:'317',stateId:'19',name:'Anuppur'},
    {id:'318',stateId:'19',name:'Ashoknagar'},
    {id:'319',stateId:'19',name:'Balaghat'},
    {id:'320',stateId:'19',name:'Barwani'},
    {id:'321',stateId:'19',name:'Betul'},
    {id:'322',stateId:'19',name:'Bhind'},
    {id:'323',stateId:'19',name:'Bhopal'},
    {id:'324',stateId:'19',name:'Burhanpur'},
    {id:'325',stateId:'19',name:'Chhatarpur'},
    {id:'326',stateId:'19',name:'Chhindwara'},
    {id:'327',stateId:'19',name:'Damoh'},
    {id:'328',stateId:'19',name:'Datia'},
    {id:'329',stateId:'19',name:'Dewas'},
    {id:'330',stateId:'19',name:'Dhar'},
    {id:'331',stateId:'19',name:'Dindori'},
    {id:'332',stateId:'19',name:'East Nimar'},
    {id:'333',stateId:'19',name:'Guna'},
    {id:'334',stateId:'19',name:'Gwalior'},
    {id:'335',stateId:'19',name:'Harda'},
    {id:'336',stateId:'19',name:'Hoshangabad'},
    {id:'337',stateId:'19',name:'Indore'},
    {id:'338',stateId:'19',name:'Jabalpur'},
    {id:'339',stateId:'19',name:'Jhabua'},
    {id:'340',stateId:'19',name:'Katm'},
    {id:'341',stateId:'19',name:'Khargone'},
    {id:'342',stateId:'19',name:'Mandsaur'},
    {id:'343',stateId:'19',name:'Morena'},
    {id:'345',stateId:'19',name:'Narsinghpur'},
    {id:'346',stateId:'19',name:'Neemuch'},
    {id:'347',stateId:'19',name:'Niwari'},
    {id:'348',stateId:'19',name:'Panna'},
    {id:'349',stateId:'19',name:'Raisen'},
    {id:'350',stateId:'19',name:'Rajgarh'},
    {id:'351',stateId:'19',name:'Ratlam'},
    {id:'352',stateId:'19',name:'Rewa'},
    {id:'353',stateId:'19',name:'Sagar'},
    {id:'354',stateId:'19',name:'Satna'},
    {id:'355',stateId:'19',name:'Sehore'},
    {id:'356',stateId:'19',name:'Seoni'},
    {id:'357',stateId:'19',name:'Shahdol'},
    {id:'358',stateId:'19',name:'Shajapur'},
    {id:'359',stateId:'19',name:'Sheopur'},
    {id:'360',stateId:'19',name:'Sidhi'},
    {id:'361',stateId:'19',name:'Singrauli'},
    {id:'362',stateId:'19',name:'Tikamgarh'},
    {id:'363',stateId:'19',name:'Ujjain'},
    {id:'364',stateId:'19',name:'Umaria'},
    {id:'365',stateId:'19',name:'Vidisha'},
    {id:'366',stateId:'20',name:'Ahmednagar'},
    {id:'367',stateId:'20',name:'Akola'},
    {id:'368',stateId:'20',name:'Amravati'},
    {id:'369',stateId:'20',name:'Aurangabad'},
    {id:'370',stateId:'20',name:'Beed'},
    {id:'371',stateId:'20',name:'Bhandara'},
    {id:'372',stateId:'20',name:'Buldhana'},
    {id:'373',stateId:'20',name:'Chandrapur'},
    {id:'374',stateId:'20',name:'Dhule'},
    {id:'375',stateId:'20',name:'Gadchiroli'},
    {id:'376',stateId:'20',name:'Gondia'},
    {id:'377',stateId:'20',name:'Hingoli'},
    {id:'378',stateId:'20',name:'Jalgaon'},
    {id:'379',stateId:'20',name:'Jalwa'},
    {id:'380',stateId:'20',name:'Kolhapur'},
    {id:'381',stateId:'20',name:'Latur'},
    {id:'382',stateId:'20',name:'Mumbai'},
    {id:'383',stateId:'20',name:'Mumbai Suburban'},
    {id:'384',stateId:'20',name:'Nagpur'},
    {id:'385',stateId:'20',name:'Nanded'},
    {id:'386',stateId:'20',name:'Nandurbar'},
    {id:'387',stateId:'20',name:'Nashik'},
    {id:'388',stateId:'20',name:'Osmanabad'},
    {id:'389',stateId:'20',name:'Palghar'},
    {id:'390',stateId:'20',name:'Parbhani'},
    {id:'391',stateId:'20',name:'Pune'},
    {id:'392',stateId:'20',name:'Raigad'},
    {id:'393',stateId:'20',name:'Ratnagiri'},
    {id:'394',stateId:'20',name:'Sangli'},
    {id:'395',stateId:'20',name:'Satara'},
    {id:'396',stateId:'20',name:'Sindhudurg'},
    {id:'397',stateId:'20',name:'Solapur'},
    {id:'398',stateId:'20',name:'Thane'},
    {id:'399',stateId:'20',name:'Wardha'},
    {id:'400',stateId:'20',name:'Washim'},
    {id:'401',stateId:'20',name:'Yavatmal'},
    {id:'402',stateId:'21',name:'Bishnupur'},
    {id:'403',stateId:'21',name:'Chandal'},
    {id:'404',stateId:'21',name:'Churachandpur'},
    {id:'405',stateId:'21',name:'Imphal East'},
    {id:'406',stateId:'21',name:'Imphal West'},
    {id:'407',stateId:'21',name:'Jiribam'},
    {id:'408',stateId:'21',name:'Kakching'},
    {id:'409',stateId:'21',name:'Kamjong'},
    {id:'410',stateId:'21',name:'Kangpokpi'},
    {id:'411',stateId:'21',name:'Money'},
    {id:'412',stateId:'21',name:'Pherzawl'},
    {id:'413',stateId:'21',name:'Senapati'},
    {id:'414',stateId:'21',name:'Tamenglong'},
    {id:'415',stateId:'21',name:'Tengnoupal'},
    {id:'416',stateId:'21',name:'Thoubal'},
    {id:'417',stateId:'21',name:'Ukhrul'},
    {id:'418',stateId:'22',name:'Eart Garo Hills'},
    {id:'419',stateId:'22',name:'East Jaintia Hills'},
    {id:'420',stateId:'22',name:'East Khasi Hills'},
    {id:'421',stateId:'22',name:'North Garo Hills'},
    {id:'422',stateId:'22',name:'RI Bhoi'},
    {id:'423',stateId:'22',name:'South Garo Hills'},
    {id:'424',stateId:'22',name:'South West Garo Hills'},
    {id:'425',stateId:'22',name:'South West Khasi Hills'},
    {id:'426',stateId:'22',name:'West Garo Hills'},
    {id:'427',stateId:'22',name:'West Jaintia Hills'},
    {id:'428',stateId:'22',name:'West Khasi Hills'},
    {id:'429',stateId:'23',name:'Aizawl'},
    {id:'430',stateId:'23',name:'Champhai'},
    {id:'431',stateId:'23',name:'Hnahthial'},
    {id:'432',stateId:'23',name:'Khawzawl'},
    {id:'433',stateId:'23',name:'Kolasib'},
    {id:'434',stateId:'23',name:'Lawngtlai'},
    {id:'435',stateId:'23',name:'Lunglei'},
    {id:'436',stateId:'23',name:'Mamit'},
    {id:'437',stateId:'23',name:'Saiha'},
    {id:'438',stateId:'23',name:'Saitual'},
    {id:'439',stateId:'23',name:'Serchhip'},
    {id:'440',stateId:'24',name:'Na'},
    {id:'441',stateId:'25',name:'Dimapur'},
    {id:'442',stateId:'25',name:'Kiphire'},
    {id:'443',stateId:'25',name:'Kohima'},
    {id:'444',stateId:'25',name:'Longleng'},
    {id:'445',stateId:'25',name:'Mokokchung'},
    {id:'446',stateId:'25',name:'Mon'},
    {id:'447',stateId:'25',name:'Peren'},
    {id:'448',stateId:'25',name:'Phek'},
    {id:'449',stateId:'25',name:'Tuensang'},
    {id:'450',stateId:'25',name:'Wokha'},
    {id:'451',stateId:'25',name:'Zunheboto'},
    {id:'452',stateId:'26',name:'Anugul'},
    {id:'453',stateId:'26',name:'Balangir'},
    {id:'454',stateId:'26',name:'Baleshwar'},
    {id:'455',stateId:'26',name:'Bargarh'},
    {id:'256',stateId:'26',name:'Bhadrak'},
    {id:'457',stateId:'26',name:'Boudh'},
    {id:'458',stateId:'26',name:'Cuttack'},
    {id:'459',stateId:'26',name:'Deogarh'},
    {id:'460',stateId:'26',name:'Dhenkanal'},
    {id:'461',stateId:'26',name:'Gajapati'},
    {id:'462',stateId:'26',name:'Ganjam'},
    {id:'463',stateId:'26',name:'Jagatsinghapur'},
    {id:'464',stateId:'26',name:'Jajapur'},
    {id:'465',stateId:'26',name:'Jharsuguda'},
    {id:'466',stateId:'26',name:'Kalahandi'},
    {id:'467',stateId:'26',name:'Kandhamal'},
    {id:'468',stateId:'26',name:'Kendrapara'},
    {id:'469',stateId:'26',name:'Kendujhar'},
    {id:'470',stateId:'26',name:'Khordha'},
    {id:'471',stateId:'26',name:'Koraput'},
    {id:'472',stateId:'26',name:'Malkangiri'},
    {id:'473',stateId:'26',name:'Mayurbhanj'},
    {id:'474',stateId:'26',name:'Nabarangpur'},
    {id:'475',stateId:'26',name:'Nayagarh'},
    {id:'476',stateId:'26',name:'Naupada'},
    {id:'477',stateId:'26',name:'Puri'},
    {id:'478',stateId:'26',name:'Rayagada'},
    {id:'479',stateId:'26',name:'Sambalpur'},
    {id:'480',stateId:'26',name:'Sonepur'},
    {id:'481',stateId:'26',name:'Sundargarh'},
    {id:'482',stateId:'27',name:'PAN India'},
    {id:'483',stateId:'28',name:'Karaikal'},
    {id:'484',stateId:'28',name:'Mahe'},
    {id:'485',stateId:'28',name:'Pondicherry'},
    {id:'486',stateId:'28',name:'Yanam'},
    {id:'487',stateId:'29',name:'Amritsar'},
    {id:'488',stateId:'29',name:'Barnala'},
    {id:'489',stateId:'29',name:'Bathinda'},
    {id:'490',stateId:'29',name:'Faridkot'},
    {id:'491',stateId:'29',name:'Fatehgarh Sahib'},
    {id:'492',stateId:'29',name:'Fazilka'},
    {id:'493',stateId:'29',name:'Firozepur'},
    {id:'494',stateId:'29',name:'Gurdaspur'},
    {id:'495',stateId:'29',name:'Hoshiarpur'},
    {id:'496',stateId:'29',name:'Jalandar'},
    {id:'497',stateId:'29',name:'Kapurthala'},
    {id:'498',stateId:'29',name:'Ludhiana'},
    {id:'499',stateId:'29',name:'Mansa'},
    {id:'500',stateId:'29',name:'Moga'},
    {id:'501',stateId:'29',name:'Patahankot'},
    {id:'502',stateId:'29',name:'Patiala'},
    {id:'503',stateId:'29',name:'Rupnagar'},
    {id:'504',stateId:'29',name:'S.A.S Nagar'},
    {id:'505',stateId:'29',name:'Sangrur'},
    {id:'506',stateId:'29',name:'Shafhid Bhagat Singh Nagar'},
    {id:'507',stateId:'29',name:'Sri Muktsar Sahib'},
    {id:'508',stateId:'29',name:'Tarn Taran'},
    {id:'509',stateId:'30',name:'Ajmer'},
    {id:'510',stateId:'30',name:'Alwar'},
    {id:'511',stateId:'30',name:'Banswara'},
    {id:'512',stateId:'30',name:'Baran'},
    {id:'513',stateId:'30',name:'Barmer'},
    {id:'514',stateId:'30',name:'Bharatpur'},
    {id:'515',stateId:'30',name:'Bhilwara'},
    {id:'516',stateId:'30',name:'Bikaner'},
    {id:'517',stateId:'30',name:'Bundi'},
    {id:'518',stateId:'30',name:'Chittorgarh'},
    {id:'519',stateId:'30',name:'Churu'},
    {id:'520',stateId:'30',name:'Dausa'},
    {id:'521',stateId:'30',name:'Dholpur'},
    {id:'522',stateId:'30',name:'Hanumangarh'},
    {id:'523',stateId:'30',name:'Jaipur'},
    {id:'524',stateId:'30',name:'Jaisalmer'},
    {id:'525',stateId:'30',name:'Jalore'},
    {id:'526',stateId:'30',name:'Jhalawar'},
    {id:'527',stateId:'30',name:'Jhunjhunu'},
    {id:'528',stateId:'30',name:'Jodhpur'},
    {id:'529',stateId:'30',name:'Karauli'},
    {id:'530',stateId:'30',name:'Nagaur'},
    {id:'531',stateId:'30',name:'Pali'},
    {id:'532',stateId:'30',name:'Pratapgarh'},
    {id:'533',stateId:'30',name:'Rajsamand'},
    {id:'534',stateId:'30',name:'Sawai Madhopur'},
    {id:'535',stateId:'30',name:'Sikar'},
    {id:'536',stateId:'30',name:'Sirohi'},
    {id:'537',stateId:'30',name:'Sri Ganganagar'},
    {id:'538',stateId:'30',name:'Tonk'},
    {id:'539',stateId:'30',name:'Udaipur'},
    {id:'540',stateId:'31',name:'East District'},
    {id:'541',stateId:'31',name:'North District'},
    {id:'542',stateId:'31',name:'South District'},
    {id:'543',stateId:'31',name:'West District'},
    {id:'545',stateId:'32',name:'Ariyalur'},
    {id:'546',stateId:'32',name:'Chengalpattu'},
    {id:'547',stateId:'32',name:'Chennai'},
    {id:'548',stateId:'32',name:'Coimbatore'},
    {id:'549',stateId:'32',name:'Cuddalore'},
    {id:'550',stateId:'32',name:'Dharmapuri'},
    {id:'551',stateId:'32',name:'Dindigu'},
    {id:'552',stateId:'32',name:'Erode'},
    {id:'553',stateId:'32',name:'Kallakurichi'},
    {id:'554',stateId:'32',name:'Kanchipuram'},
    {id:'555',stateId:'32',name:'Kanyakumari'},
    {id:'556',stateId:'32',name:'Karur'},
    {id:'557',stateId:'32',name:'Krishnagiri'},
    {id:'558',stateId:'32',name:'Madurai'},
    {id:'559',stateId:'32',name:'Nagapattinam'},
    {id:'560',stateId:'32',name:'Namakkal'},
    {id:'561',stateId:'32',name:'Nilgiris'},
    {id:'562',stateId:'32',name:'Perambalur'},
    {id:'563',stateId:'32',name:'Pudukkottai'},
    {id:'564',stateId:'32',name:'Ramanathapuram'},
    {id:'565',stateId:'32',name:'Ranipet'},
    {id:'566',stateId:'32',name:'Salem'},
    {id:'567',stateId:'32',name:'Sivaganga'},
    {id:'568',stateId:'32',name:'Tenkasi'},
    {id:'569',stateId:'32',name:'Thanjavur'},
    {id:'570',stateId:'32',name:'Theni'},
    {id:'571',stateId:'32',name:'Thoothukudi'},
    {id:'572',stateId:'32',name:'Tiruchirappalli'},
    {id:'573',stateId:'32',name:'Tirunelveli'},
    {id:'574',stateId:'32',name:'Tirupathur'},
    {id:'575',stateId:'32',name:'Tiruppur'},
    {id:'576',stateId:'32',name:'Tiruvallur'},
    {id:'577',stateId:'32',name:'Tiruvannamalai'},
    {id:'578',stateId:'32',name:'Tiruvarur'},
    {id:'579',stateId:'32',name:'Vellore'},
    {id:'580',stateId:'32',name:'Viluppuram'},
    {id:'581',stateId:'32',name:'Virudhunagar'},
    {id:'582',stateId:'33',name:'Adilabad'},
    {id:'583',stateId:'33',name:'Bhadradri'},
    {id:'584',stateId:'33',name:'Kothagudem'},
    {id:'585',stateId:'33',name:'Hyderabad'},
    {id:'586',stateId:'33',name:'Jagtial'},
    {id:'587',stateId:'33',name:'Jangaon'},
    {id:'588',stateId:'33',name:'Jayashankar'},
    {id:'589',stateId:'33',name:'Bhoopalpally'},
    {id:'590',stateId:'33',name:'Jogulamba Gadwal'},
    {id:'591',stateId:'33',name:'Kamareddy'},
    {id:'592',stateId:'33',name:'Karimnagar'},
    {id:'593',stateId:'33',name:'Khammam'},
    {id:'594',stateId:'33',name:'Komaram Bheem asifabad'},
    {id:'595',stateId:'33',name:'Mahabubnagar'},
    {id:'596',stateId:'33',name:'Mancherial'},
    {id:'597',stateId:'33',name:'Medak'},
    {id:'598',stateId:'33',name:'Medchal'},
    {id:'599',stateId:'33',name:'Nalgonda'},
    {id:'600',stateId:'33',name:'Nirmal'},
    {id:'601',stateId:'33',name:'Nizamabad'},
    {id:'602',stateId:'33',name:'Peddapalli'},
    {id:'603',stateId:'33',name:'Rajannna Sircilla'},
    {id:'604',stateId:'33',name:'Rangareddy'},
    {id:'605',stateId:'33',name:'Sangareddy'},
    {id:'606',stateId:'33',name:'Siddipet'},
    {id:'607',stateId:'33',name:'Suryapet'},
    {id:'608',stateId:'33',name:'Vikarbed'},
    {id:'609',stateId:'33',name:'Wanaparthy'},
    {id:'610',stateId:'33',name:'Warangal(Rural)'},
    {id:'611',stateId:'33',name:'Warangal(Urban)'},
    {id:'612',stateId:'33',name:'Yadadri Bhuvanagiri'},
    {id:'613',stateId:'34',name:'Dadra and Nagar Haveli'},
    {id:'614',stateId:'34',name:'Daman'},
    {id:'615',stateId:'34',name:'Diu'},
    {id:'616',stateId:'35',name:'Dhalai'},
    {id:'617',stateId:'35',name:'Gomati'},
    {id:'618',stateId:'35',name:'Khowai'},
    {id:'619',stateId:'35',name:'North Tripura'},
    {id:'620',stateId:'35',name:'Sepahijla'},
    {id:'621',stateId:'35',name:'South Tripura'},
    {id:'622',stateId:'35',name:'Unakoti'},
    {id:'623',stateId:'35',name:'West Tripura'},
    {id:'624',stateId:'36',name:'Agra'},
    {id:'625',stateId:'36',name:'Aligarh'},
    {id:'626',stateId:'36',name:'Ambedkar Nagar'},
    {id:'627',stateId:'36',name:'Amethi'},
    {id:'628',stateId:'36',name:'Amroha'},
    {id:'629',stateId:'36',name:'Auraiya'},
    {id:'630',stateId:'36',name:'Ayodhya'},
    {id:'631',stateId:'36',name:'Azamgarh'},
    {id:'632',stateId:'36',name:'Baghpat'},
    {id:'633',stateId:'36',name:'Bahraich'},
    {id:'634',stateId:'36',name:'Ballia'},
    {id:'635',stateId:'36',name:'Balrampur'},
    {id:'636',stateId:'36',name:'Banda'},
    {id:'637',stateId:'36',name:'Barabanki'},
    {id:'638',stateId:'36',name:'Bareilly'},
    {id:'639',stateId:'36',name:'Basti'},
    {id:'640',stateId:'36',name:'Bhadohi'},
    {id:'641',stateId:'36',name:'Bijnor'},
    {id:'642',stateId:'36',name:'Badaun'},
    {id:'643',stateId:'36',name:'Balandshahr'},
    {id:'644',stateId:'36',name:'Chandauli'},
    {id:'645',stateId:'36',name:'Chitrakoot'},
    {id:'646',stateId:'36',name:'Deoria'},
    {id:'647',stateId:'36',name:'Etah'},
    {id:'648',stateId:'36',name:'Etawah'},
    {id:'649',stateId:'36',name:'Farrukhabad'},
    {id:'650',stateId:'36',name:'Fatehpur'},
    {id:'651',stateId:'36',name:'Firozabad'},
    {id:'652',stateId:'36',name:'Guatam Buddha Nagar'},
    {id:'653',stateId:'36',name:'Ghaziabad'},
    {id:'654',stateId:'36',name:'Ghazipur'},
    {id:'655',stateId:'36',name:'Gonda'},
    {id:'656',stateId:'36',name:'Gorakhpur'},
    {id:'657',stateId:'36',name:'Hamirpur'},
    {id:'658',stateId:'36',name:'Hapur'},
    {id:'659',stateId:'36',name:'Hardoi'},
    {id:'660',stateId:'36',name:'Hathras'},
    {id:'661',stateId:'36',name:'Jaluan'},
    {id:'662',stateId:'36',name:'Jaunpur'},
    {id:'663',stateId:'36',name:'Jhansi'},
    {id:'664',stateId:'36',name:'Kannauj'},
    {id:'665',stateId:'36',name:'Kanpur Dehat'},
    {id:'666',stateId:'36',name:'Kanpur Nagar'},
    {id:'667',stateId:'36',name:'Kasganj'},
    {id:'668',stateId:'36',name:'Kaushambi'},
    {id:'669',stateId:'36',name:'Kheri'},
    {id:'670',stateId:'36',name:'Kushi Nagar'},
    {id:'671',stateId:'36',name:' Lalitpur'},
    {id:'672',stateId:'36',name:'Lucknow'},
    {id:'673',stateId:'36',name:'Maharajganj'},
    {id:'674',stateId:'36',name:'Mahoba'},
    {id:'675',stateId:'36',name:'Mainpuri'},
    {id:'676',stateId:'36',name:'Mathura'},
    {id:'677',stateId:'36',name:'Mau'},
    {id:'678',stateId:'36',name:'Meerut'},
    {id:'679',stateId:'36',name:'Mirzapur'},
    {id:'680',stateId:'36',name:'Moradabad'},
    {id:'681',stateId:'36',name:'Muzaffarnagar'},
    {id:'682',stateId:'36',name:'Pilibhit'},
    {id:'683',stateId:'36',name:'Pratapgarh'},
    {id:'684',stateId:'36',name:'Prayagraj'},
    {id:'685',stateId:'36',name:'Rae Bareli'},
    {id:'686',stateId:'36',name:'Rampur'},
    {id:'687',stateId:'36',name:'Saharanpur'},
    {id:'628',stateId:'36',name:'Sambhal'},
    {id:'689',stateId:'36',name:'Sant Kabeer Nagar'},
    {id:'690',stateId:'36',name:'Shahjahanpur'},
    {id:'691',stateId:'36',name:'Shamli'},
    {id:'692',stateId:'36',name:'Shravasti'},
    {id:'693',stateId:'36',name:'Siddharth Nagar'},
    {id:'694',stateId:'36',name:'Sultanpur'},
    {id:'695',stateId:'36',name:'Unnao'},
    {id:'696',stateId:'36',name:'Varanasi'},
    {id:'697',stateId:'36',name:'Sitapur'},
    {id:'698',stateId:'36',name:'Sonbhadra'},
    {id:'699',stateId:'36',name:''},
    {id:'700',stateId:'36',name:''},
    {id:'703',stateId:'37',name:'Almora'},
    {id:'704',stateId:'37',name:'Bageshwar'},
    {id:'705',stateId:'37',name:'Chamoli'},
    {id:'706',stateId:'37',name:'Champawat'},
    {id:'707',stateId:'37',name:'Dehradun'},
    {id:'708',stateId:'37',name:'Haridwar'},
    {id:'709',stateId:'37',name:'Nainital'},
    {id:'710',stateId:'37',name:'Pauri Garhwal'},
    {id:'711',stateId:'37',name:'Pithoragarh'},
    {id:'712',stateId:'37',name:'Rudra Prayag'},
    {id:'713',stateId:'37',name:'Tehri Garhwal'},
    {id:'714',stateId:'37',name:'Udam Singh Nagar'},
    {id:'715',stateId:'37',name:'Uttar Kashi'},
    {id:'716',stateId:'38',name:'Alipurduar'},
    {id:'717',stateId:'38',name:'Bankura'},
    {id:'718',stateId:'38',name:'Birbhum'},
    {id:'719',stateId:'38',name:'Cooch Behar'},
    {id:'720',stateId:'38',name:'Dakshin Dinajpur'},
    {id:'721',stateId:'38',name:'Darjeeling'},
    {id:'722',stateId:'38',name:'Hooghly'},
    {id:'723',stateId:'38',name:'Howrah'},
    {id:'724',stateId:'38',name:'Jalpaiguri'},
    {id:'725',stateId:'38',name:'Jhargram'},
    {id:'726',stateId:'38',name:'Kalimpong'},
    {id:'727',stateId:'38',name:'Kolkata'},
    {id:'728',stateId:'38',name:'Malda'},
    {id:'729',stateId:'38',name:'Murshidabad'},
    {id:'730',stateId:'38',name:'Nadia'},
    {id:'731',stateId:'38',name:'North 24 Parganas'},
    {id:'732',stateId:'38',name:'Paschim Medinipur'},
    {id:'733',stateId:'38',name:'Paschim (West) Burdwan'},
    {id:'734',stateId:'38',name:'Purba Burdwan'},
    {id:'735',stateId:'38',name:'Purba Medinipur'},
    {id:'736',stateId:'38',name:'Purulia'},
    {id:'737',stateId:'28',name:'South 24 Parganas'},
    {id:'738',stateId:'38',name:'Uttar Dinajpur'},

        ]
export const userlistdata=[
    {
        id:"1",
        image:process.env.PUBLIC_URL + `/images/logo1.png`,
        title:"Beauty",
        subtitle:"SK jain General store",
        description:"Sk Jain General Store,Gohana Road Rohtak,Rohtak,Haryana"
    },
    {
        id:"2",
        image:process.env.PUBLIC_URL + `/images/logo1.png`,
        title:"Real State",
        subtitle:"Property Advisor",
        description:"Gohana Road Rohtak,Gohana Road ,Rohtak,Haryana,Rohtak"
    }
]